# Generated by Django 6.0 on 2025-12-20 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 20, 12, 55, 16, 634819, tzinfo=datetime.timezone.utc)),
        ),
    ]
